/// Generated by AssetsRefGenerator on 2021/11/24
class Res {
  static const String Cairo_Black = "assets/fonts/Cairo-Black.ttf";
  static const String Cairo_Bold = "assets/fonts/Cairo-Bold.ttf";
  static const String Cairo_ExtraLight = "assets/fonts/Cairo-ExtraLight.ttf";
  static const String Cairo_Light = "assets/fonts/Cairo-Light.ttf";
  static const String Cairo_Regular = "assets/fonts/Cairo-Regular.ttf";
  static const String Cairo_SemiBold = "assets/fonts/Cairo-SemiBold.ttf";
  static const String female = "assets/images/female.png";
  static const String icons = "assets/fonts/icons.ttf";
  static const String logo = "assets/images/logo.png";
  static const String male = "assets/images/male.png";
  static const String OFL = "assets/fonts/OFL.txt";
  static const String t2 = "assets/icon/t2.png";
}
